events2/urls.py
from django.urls import include, path
from . import views


app_name = 'events2'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/register/', views.register, name='register')
]

eventstud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('events1/', include('events.urls')),
    path('events/', include('events2.urls')),
    path('news/', include('newspage.urls')),
    path('registermember/', include('register_member.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('aboutUs/', include('aboutus_page.urls')),
    path('history/', include('history.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout , name='logout'),
    path('is_login/', views.is_login, name ='is_login'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.contrib.auth import logout as auth_logout
from django.shortcuts import render
from events2.models import Event
from django.http import HttpResponseRedirect, JsonResponse

def index(request):
    response = {}
    response["event_list"] = Event.objects.all()[:3]
    return render(request, 'home/hello.html', response)

def logout(request):
	if request.user.is_authenticated:
		auth_logout(request)
	return HttpResponseRedirect('/')

def is_login(request):
	if request.user.is_authenticated:
		return JsonResponse({'login': True})
	return JsonResponse({'login': False})

home/templates/home/hello.html
{% extends 'eventstud/base.html' %}
{% load static %}

{% block navbar %}
{% with current_nav='home' %}
{{ block.super }}
{% endwith %}
{% endblock navbar%}

{% block body %}
{{ block.super }}
	<div id="header-image" class="jumbotron text-white">
		<div class="centerme">
			<h1 align="center"><span class="font-weight-light">CREATE AND JOIN</span>
			<span class="font-weight-bold">EVENTS</span>
			<span class="font-weight-light">MORE EASILY</span>
			</h1>
		</div>
	</div>

	<div class="container">
		<center><h3>MARK YOUR DATE!</h3></center>
		<br>
		<br>
	</div>

	<div class="col-sm">
		<div class="card-columns">
			{% for event in event_list %}
			<div class="card bg-dark text-white">
				<img id="card-img-culture" class="card-img-top" src="{{ event.thumbnail_image_url }}" alt="2017-900x506-afm-hero" alt="Card image">
				<div class="card-body">
					<h4 class="card-title">{{ event.title }}</h4>
					<span><p class="card-text"><img src="https://image.flaticon.com/icons/svg/33/33700.svg" width="25px">  {{ event.organizer_email }}</span></p>
					<span><p class="card-date"><img src="https://image.flaticon.com/icons/svg/747/747310.svg" width="25px">  {{ event.time_start.date }}</span></p>
					<a href="{% url 'events2:detail' event.pk %}" class="float-right btn btn-dark purple-background dark-text">JOIN</a>
				</div>
			</div>
			{% endfor %}
		</div>
	</div>
	<link rel="stylesheet" href="{% static 'css/style_home.css' %}"
{% endblock body %}