aboutus_page/urls.py
from django.urls import path
from .views import *

app_name = 'aboutus_page'
urlpatterns = [
    path('', index, name="index"),
    path('save/', save_testimoni, name="save_testimoni")
]

events2/urls.py
from django.urls import include, path
from . import views


app_name = 'events2'
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/register/', views.register, name='register')
]

eventstud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('events1/', include('events.urls')),
    path('events/', include('events2.urls')),
    path('news/', include('newspage.urls')),
    path('registermember/', include('register_member.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('aboutUs/', include('aboutus_page.urls')),
    path('history/', include('history.urls')),
]

history/urls.py
from .views import historyPage
from .views import dataRegistered
from django.conf.urls import url

app_name = 'history'
urlpatterns = [
	url(r'^$', historyPage, name = 'historyPage'),
	url(r'^data/', dataRegistered, name = 'dataRegistered'),
	
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout , name='logout'),
    path('is_login/', views.is_login, name ='is_login'),
]

newspage/urls.py
from .views import tampilNews
from .views import beritaFull
from django.conf.urls import url

app_name = 'newspage'
urlpatterns = [
	url(r'^$', tampilNews, name = 'tampilNews'),
	url(r'^(?P<nomor>.*)/$', beritaFull, name = 'beritaFull'),
]

templates/eventstud/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <title>{% block title %}eventstud{% endblock title %}</title>
  </head>
  <body>
  {% block body %}
    <header>
      {% block navbar %}
      {% include 'eventstud/navbar.html' with current_nav=current_nav %}
      {% endblock navbar %}
    </header>
  {% endblock body %}
  {% block footer %}
    {% include 'eventstud/footer.html' %}
  {% endblock footer %}
  {% block style %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% endblock style %}
  {% block scripts %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  {% endblock scripts%}
  </body>
</html>

templates/eventstud/footer.html
<footer class="page-footer font-small">
	<div class="container">
		<div class="row text-center">
			<div class="col-sm py-4">
				<span>
					<img class="m-3" src="https://image.flaticon.com/icons/svg/149/149984.svg" height="50px">
					<p class="card-tex font-weight-bold">
						Jl. Prof. Dr. Nugroho Notosutanto, Depok, Beji, Pondok Cina
					</p>
				</span>
			</div>
			<div class="col-sm py-4">
				<span>
          <img class="m-3" src="https://image.flaticon.com/icons/svg/9/9243.svg" height="50px">
          <p class="card-text font-weight-bold">
          Phone: +62 21368 254 09
          </p>
        </span>
			</div>
			<div class="col-sm py-4">
				<span>
          <img class="m-3" src="https://image.flaticon.com/icons/svg/181/181535.svg" height="50px">
          <p class="card-text font-weight-bold">
          EventStud@gmail.com
          </p>
        </span>
			</div>
		</div>
	</div>
	<div class="footer-expand-md footer-dark footer-custom-bg absolute-bottom text-white">
		<div class="footer-text text-center py-3 font-weight-light">© 2018 — EventStud</div>
	</div>
</footer>

templates/eventstud/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark navbar-custom-bg sticky-top">
    <a class="navbar-brand font-weight-bold" href="{% url 'home:index' %}">EVENT STUD</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav px-5">
            <li class="nav-item mx-3">
                <a class="nav-link{% if current_nav == 'home' %} font-weight-bold{% endif %}" href="{% url 'home:index' %}">HOME</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link{% if current_nav == 'register' %} font-weight-bold{% endif %}" href="{% url 'register_member:index' %}">REGISTER</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link{% if current_nav == 'news' %} font-weight-bold{% endif %}" href="{% url 'newspage:tampilNews' %}">NEWS</a>
            </li>
            <li class="nav-item mx-3">
                <a class="nav-link{% if current_nav == 'events' %} font-weight-bold{% endif %}" href="{% url 'events2:index' %}">EVENTS</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item mx-3">
                <a class="nav-link{% if current_nav == 'registered' %} font-weight-bold{% endif %}" href="{% url 'history:historyPage' %}">REGISTERED</a>
            </li>
          {% endif %}
            <li class="nav-item mx-3">
                <a class="nav-link{% if current_nav == 'about' %} font-weight-bold{% endif %}" href="{% url 'aboutus_page:index' %}">ABOUT US</a>
            </li>

            {% if user.is_authenticated %}
            <a class="p nav-link navbar-nav" href= "{% url 'home:logout'%}">
              <span class="text-white" style="padding-right: 10px">Hello, {{ user.username }}</span>
              <div class="left">
                <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
              </div> Log Out</a>
          {% else %}
          <a class="tulisan nav-link navbar-nav" href="{% url 'social:begin' 'google-oauth2' %}" style="text-transform:none">
              <center><div class="left">
                  <img width="20px" alt="Google &quot;G&quot; Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Google_%22G%22_Logo.svg/512px-Google_%22G%22_Logo.svg.png"/>
              </div> Login with Google
              </center>
          </a>
          {% endif %}
        </ul>
    </div>
</nav>